language: generic

services:
  - docker

before_install:
  - docker build -t unkeep/alfabooker .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push unkeep/alfabooker
  - cd aws

deploy:
  provider: elasticbeanstalk
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  region: "eu-central-1"  
  app: "alfabooker"
  env: "Alfabooker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-497796177862"
  on:
    branch: master
  